export { default as AntrianDokter } from './AntrianDokter'
export { default as DashboardDokter } from './DashboardDokter'
export { default as DetailAntrian } from './DetailAntrian'
export { default as DokterLayout } from './DokterLayout'
export { default as ProfilDokter } from './ProfilDokter'